version: '3'
services:
  spark:
    image: bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/opt/bitnami/spark/app/:/opt/bitnami/spark/python/
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ./csv:/opt/bitnami/spark/app
  spark-worker:
    image: bitnami/spark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/opt/bitnami/spark/app/:/opt/bitnami/spark/python/
    volumes:
      - ./csv:/opt/bitnami/spark/app
  
  streamsets:
   image: bim81929/streamsets
   ports:
     - 18630:18630
  
  jupyter:
    image: jupyter/all-spark-notebook:spark-3.3.0
    volumes:
      - ./spark:/home/jovyan/work
      - ./csv:/opt/bitnami/spark/app
    ports:
      - "8888:8888"
  
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
