version: '3'
services:
  spark:
    image: bim81929/pyspark:3.3.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/opt/bitnami/spark/python/
      - PYSPARK_PYTHON=3.10.6
      - PYSPARK_DRIVER_PYTHON=3.10.6
    ports:
      - 7077:7077
      - 8080:8080
  spark-worker:
    image: bim81929/pyspark:3.3.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - PYTHONPATH=/opt/bitnami/spark/python/
      - PYSPARK_PYTHON=3.10.6
      - PYSPARK_DRIVER_PYTHON=3.10.6
  
  # streamsets:
  #  image: bim81929/streamsets
  #  ports:
  #    - 18630:18630
  
  jupyter:
    image: bim81929/jupyter
    volumes:
      - ./spark:/home/jovyan/work
    ports:
      - "8888:8888"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
volumes:
  minio_storage: {}

# wZPhSZYqzYwCwZBG7H9F
# laK81FcRGl6Kd6JXi1EYA5V7HGzG25ReFMbpwfKN